#-------------------------------
# 管理員功能設定：
admin:

  #-----------------------------
  # /公告 指令的設定：
  announcement:

    # 標題使用的 emoji。
    emoji: "📢"


  #-----------------------------
  # /刪除訊息 指令的設定：
  messageDelete:
    emoji: "🗑️"

    # 刪除訊息的最大數量，最多支援一次刪除 100 則訊息。
    deleteLimit: 30


  #-----------------------------
  # /直播 指令的設定：
  stream:
    
    # 要提及的身分組 ID ，若不填寫則預設為 @everyone
    role: " "

    # 發送直播公告時，附加的自定義隨機訊息，可繼續往下延伸。
    message:
      - "現在正直播精彩內容，來一起加入吧！"
      - "直播現在開始！別錯過，一起觀看吧！"
      - "開播啦！一起享受這場直播！"

    # 要監控的 twitch 使用者 ID
    twitchUserID: " "

    # 要監控的 twitch 使用者頭像網址
    twitchUserAvatar: " "


#-------------------------------
# /關於 相關設定：
about:
  emoji: "🔰"

  # 機器人的暱稱（將用於部分指令，請勿使用大寫英文或空格）
  botNickname: "みやこ"

  # 機器人的介紹
  introduce: "みやこ機器人第三代！\n這是一個基於 discord.js 集合許多功能的綜合型機器人，\n本專案目前仍在積極開發中！"

  # 服務提供者，請填入您的 Discord 數字 ID
  provider: " "

  # 專案連結
  repository: "https://github.com/miguotw/MiYako-DCB"


#-------------------------------
# /延遲 相關設定：
ping:
  emoji: "🏓"


#-------------------------------
# /一言 相關設定：
hitokoto:
  emoji: "🍵"


#-------------------------------
# /網際協定位址資訊 相關設定：
ipQuery:
  emoji: "ℹ️"


#-------------------------------
# /麥塊 相關設定：
minecraft:
  emoji: "🧱"

  #預設列表中的伺服器名稱與 IP，可繼續向下延伸，最多支援 25 個
  defaultServer:
    Hypixel: "mc.hypixel.net"


#-------------------------------
# /時間戳 相關設定：
unixTimestamp:
  emoji: "🕒"