#-------------------------------
# 啟動設定：
Startup:

  # 機器人的 token
  token: " "

  # 機器人的 ID
  clientID: " "

  # 機器人的活動狀態，可參考：0 正在玩、1 正在直播、2 正在聽、3 正在看、5競爭
  activityType: 0

  # 機器人的線上狀態，可參考：online (線上)、idle (閒置/離開)、dnd (請勿打擾)、invisible (隱身)
  StatusType: "online"

#-------------------------------
# 日誌設定：
log:

  # 日誌頻道 ID
  channel: " "

  # 時區偏移
  timezone: 0


#-------------------------------
# 嵌入介面通用設定：
embed:
  color:
    default: 0x1abc9c
    success: 0x242429
    error: 0x242429


#-------------------------------
# 表情符號通用設定
emoji:
  success: "✅"
  error: "❌"
  loading: "..."
