#-------------------------------
# 成員加入與離開伺服器 相關設定：
member:

  # 成員加入與離開伺服器時，發送的訊息上的標題使用的 emoji。
  emoji:
    join: "🚧"
    leave: "🚧"

  # 成員加入與離開伺服器時，發送的訊息內容。
  message:
    join:
      - "歡迎來到伺服器！"
      - "社群有你更精彩！"
      - "歡迎加入我們的大家庭！"

    leave:
      - "感謝你的陪伴，希望未來還能再見～"
      - "雖然你離開了，但你的足跡永遠留在我們的心中～"
      - "雖然心中不捨，但希望你一切順利～"

  # 成員加入與離開伺服器時，是否發送記錄到日誌頻道。
  enable: true


#-------------------------------
# 成員訊息 相關設定：
message:

  # 成員傳送、編輯、刪除訊息時，是否發送記錄到日誌頻道。
  enable:
    create: false
    update: true
    delete: true


#-------------------------------
# 成員身分組 相關設定：
role:

  # 成員身分組被變更時，是否發送記錄到日誌頻道。
  enable: true


#-------------------------------
# 成員語音活動 相關設定：
voice:

  # 成員加入、離開語音頻道時，是否發送記錄到日誌頻道。
  enable: true


#-------------------------------
# 關鍵字觸發 相關設定：
keywords:

  # 是否啟用白名單功能。
  # 當啟用白名單功能時，機器人只會在 channels 中的頻道觸發關鍵字。
  # 當禁用白名單功能時，機器人不會在 channels 中的頻道觸發關鍵字。
  whitelist: false 

  # 頻道列表。
  channels: 
    - "1334932660581175386"

  # 冷卻時間(以豪秒為單位)，機器人會等待一段時間才回復消息。
  cooldown: 2000

  # 關鍵字觸發時，是否發送記錄到日誌頻道。
  enable: true

  # 觸發關鍵字的關鍵字列表。
  triggers:
    01:
      keywords: 
        - "???"
      responses: 
        - "???"

    02:
      keywords: 
        - "佛心"
      responses: 
        - "╰(⊙Д⊙)╮佛心公司╭(⊙Д⊙)╯"

    03:
      keywords: 
        - "差低"
        - "XD"
      responses: 
        - "差低"
        - "XD"