#-------------------------------
# 成員加入與離開伺服器 相關設定：
member:

  # 成員加入與離開伺服器時，是否發送記錄到日誌頻道。
  enable: false


#-------------------------------
# 成員訊息 相關設定：
message:

  # 成員傳送、編輯、刪除訊息時，是否發送記錄到日誌頻道。
  enable:
    create: false
    update: false
    delete: false


#-------------------------------
# 成員身分組 相關設定：
role:

  # 成員身分組被變更時，是否發送記錄到日誌頻道。
  enable: false


#-------------------------------
# 成員語音活動 相關設定：
voice:

  # 成員加入、離開語音頻道時，是否發送記錄到日誌頻道。
  enable: false